Add keyboard structs
frikadelki/telegram-bot-api pull request #8
Opened 2016-10-15 12:31 UTC by dmoroz0v

TgmReplyKeyboardMarkup keyboardMarkup = TgmReplyKeyboardMarkup
	.builder()
	.row(new ArrayList<TgmKeyboardButton>(){{
		add(TgmKeyboardButton
			.builder()
			.text("Action1")
			.requestContact(true)
			.build()
		);
		add(new TgmKeyboardButton(
			"Action2",
			TgmKeyboardButton.Type.LOCATION
			)
		);
	}})
	.build();

TgmReplyKeyboardHide keyboardHide = TgmReplyKeyboardHide
	.builder()
	.hideKeyboard(true)
	.selective(true)
	.build();

2016-10-16 16:46 UTC, frikadelki requested changes
Ну в общем по мелочам там написал.
Идеологически. Часа два думал стоит оно того или нет. В общем мне кажется что стоит. Сделать классы по максимуму иммутабельными и максимально закрытыми. То есть везде где можно и не вызывает напрягов - фигакнуть final на поля (мне кажется можно везде кроме поле запроса локации и контакта в кнопке). И принципиально убрать везеде геттеры и сеттеры, мне кажется текущих ручных конструкторов, конструкторов и билдеров ломбока достаточно для любого извращения клиентов, а доп извражения будут доступны через твои другие билдеры.
Я вижу пару преимуществ:
- иммутабельность хорошо дружит с многопоточностью, а это типо код энтерпраз приложеня, где это норма, когда объекты высираются одним потоком, а высылаются в телеграм - другим.
- наличие геттеров это просто расширение нашего интерфеса => больше поддержки в будущем. И хотя геттеры это ни о чем, и вряд ли мы придем в ситуаци. когда нам тяжело будет их написать/поддерживать, тут есть тако вопрос. А зачем могут понадобится геттеры тут? Я могу только представить себе код вида "xxx".euals(button.getText()), т.е. ситауцию когда программист потерял контроль над доменно моделью своего бота, и начал говнокодить. Эти же вот классы, это же, ну UI, причем такая, прям write-only ведь вью.

2016-10-16 16:46 UTC, frikadelki commented on src/main/java/org/frikadelki/ash/telegram/api/keyboard/TgmKeyboardButton.java
> +@AllArgsConstructor
Мне кажется что тут обе аннотации излишни, т.к. позволят создать объект в невалидном состоянии. Достаточно вроде как наших конструкторов.

2016-10-16 16:46 UTC, frikadelki commented on src/main/java/org/frikadelki/ash/telegram/api/keyboard/TgmKeyboardButton.java
> +	public TgmKeyboardButton(String text) {
предлагаю конктрукторы фигачить первыми сразу после объявления переменных

2016-10-16 16:46 UTC, frikadelki commented on src/main/java/org/frikadelki/ash/telegram/api/keyboard/TgmKeyboardButton.java
> +	public Type getType() {
вот эту штуку я бы предложил совсем вырезать. расшифровка в саммари ревью.

2016-10-16 16:46 UTC, frikadelki commented on src/main/java/org/frikadelki/ash/telegram/api/keyboard/TgmKeyboardButton.java
> +	public void setType(Type type) {
а эту штуку сделать приватно

2016-10-16 16:46 UTC, frikadelki commented on src/main/java/org/frikadelki/ash/telegram/api/keyboard/TgmReplyKeyboardHide.java
> +public final class TgmReplyKeyboardHide {
я вот к этому, и второму реплаю накину мысль, может их для единообразия стоит назвать TgmKeyboardReply...? Даже как будто читается лучше. Ну это не принципиально.

2016-10-16 16:46 UTC, frikadelki commented on src/main/java/org/frikadelki/ash/telegram/api/keyboard/TgmKeyboardButton.java
> +package org.frikadelki.ash.telegram.api.keyboard;
мне кажется это надо двинуть в org.frikadelki.ash.telegram.api.**chat**.keyboard, т.к. идеологически же эти штуки внутри того пэкэдлжа используются. Хотя пэкэджи в джаве и сломаны.

2016-10-17 03:10 UTC, dmoroz0v commented on src/main/java/org/frikadelki/ash/telegram/api/keyboard/TgmKeyboardButton.java
> +@AllArgsConstructor
имеешь в виду не валидный в смысле оба параметра true указать, ну так документация этого не запрещает. Не вижу причин ограничивать пользователя

2016-10-17 03:11 UTC, dmoroz0v commented on src/main/java/org/frikadelki/ash/telegram/api/keyboard/TgmKeyboardButton.java
> +	public Type getType() {
согласен геттер можно вырезать

2016-10-17 03:12 UTC, dmoroz0v commented on src/main/java/org/frikadelki/ash/telegram/api/keyboard/TgmKeyboardButton.java
> +	public void setType(Type type) {
не согласен. если хочется создать с текстом, а потом решить какой тип указать

2016-10-17 03:13 UTC, dmoroz0v commented on src/main/java/org/frikadelki/ash/telegram/api/keyboard/TgmKeyboardButton.java
> +	public TgmKeyboardButton(String text) {
это да

2016-10-17 03:14 UTC, dmoroz0v commented on src/main/java/org/frikadelki/ash/telegram/api/keyboard/TgmReplyKeyboardHide.java
> +public final class TgmReplyKeyboardHide {
нет, в документации это называется:
https://core.telegram.org/bots/api/#replykeyboardmarkup
https://core.telegram.org/bots/api/#replykeyboardhide

2016-10-17 03:14 UTC, dmoroz0v commented on src/main/java/org/frikadelki/ash/telegram/api/keyboard/TgmKeyboardButton.java
> +package org.frikadelki.ash.telegram.api.keyboard;
ok

2016-10-17 03:18 UTC, frikadelki commented on src/main/java/org/frikadelki/ash/telegram/api/keyboard/TgmKeyboardButton.java
> +	public void setType(Type type) {
тогда совокупно, убрать вообще этот Type отсюда в "пиздатые" билдеры, ну или как

с одной стороны ты защищаешь пользователя, не позволяя ему создать невалидные флаги, а с другой стороны есть конструктор который разрешает делать все что хочешь.

2016-10-17 03:19 UTC, frikadelki commented on src/main/java/org/frikadelki/ash/telegram/api/keyboard/TgmReplyKeyboardHide.java
> +public final class TgmReplyKeyboardHide {
да я видел, и такая мысль тоже есть, но что-то меня гнетет в этих названиях

2016-10-17 03:23 UTC, frikadelki commented on src/main/java/org/frikadelki/ash/telegram/api/keyboard/TgmKeyboardButton.java
> +	public void setType(Type type) {
ну и сеттер опять же идет против идеи иммутабельности. 
Я короче против давать пользователю овер 100500 вариантов сделать одно и то же. Во первых пользователю непонятно какой использовать лучше, быстрее, идиоматичнее. И нам проблемы, когда мы решим что-то выпилить: либо получай гнев от пользователей, либо пишу кучу саппорт кода.

2016-10-23 19:03 UTC, frikadelki approved these changes
Я в итоге все же выкосил сеттеры, потому что иммутабельность дает много плюсов, а для случая поэтапного заполнения объекта есть ломбок-билдеры, поэтому пользователи страдать не будут. Можно провести аналогию с mvvm/mvp, апи телеграма для нас `output`, куда мы скидываем отрендеренные данные, а телеграм отображает эту инфу пользователю, а эти классы, это вью-модель зафиксированная для конкретного момента времени, или типа того.

2016-10-23 19:03 UTC, merged